// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: binding.sql

package store

import (
	"context"
)

const deleteBinding = `-- name: DeleteBinding :exec
DELETE FROM binding WHERE id = ?
`

func (q *Queries) DeleteBinding(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBinding, id)
	return err
}

const fanOutBindingsByAccountExternal = `-- name: FanOutBindingsByAccountExternal :many
SELECT id, slot_id, account_id, provider, external_id, cached_meta_json, sync_status, last_synced_at, created_at FROM binding WHERE account_id = ? AND external_id = ?
`

type FanOutBindingsByAccountExternalParams struct {
	AccountID  string
	ExternalID string
}

func (q *Queries) FanOutBindingsByAccountExternal(ctx context.Context, arg FanOutBindingsByAccountExternalParams) ([]Binding, error) {
	rows, err := q.db.QueryContext(ctx, fanOutBindingsByAccountExternal, arg.AccountID, arg.ExternalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Binding
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.AccountID,
			&i.Provider,
			&i.ExternalID,
			&i.CachedMetaJson,
			&i.SyncStatus,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBinding = `-- name: GetBinding :one
SELECT id, slot_id, account_id, provider, external_id, cached_meta_json, sync_status, last_synced_at, created_at FROM binding WHERE id = ?
`

func (q *Queries) GetBinding(ctx context.Context, id string) (Binding, error) {
	row := q.db.QueryRowContext(ctx, getBinding, id)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.AccountID,
		&i.Provider,
		&i.ExternalID,
		&i.CachedMetaJson,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertBinding = `-- name: InsertBinding :exec
INSERT INTO binding (id, slot_id, account_id, provider, external_id, cached_meta_json, sync_status, last_synced_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBindingParams struct {
	ID             string
	SlotID         string
	AccountID      string
	Provider       string
	ExternalID     string
	CachedMetaJson string
	SyncStatus     string
	LastSyncedAt   *string
	CreatedAt      string
}

func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertBinding,
		arg.ID,
		arg.SlotID,
		arg.AccountID,
		arg.Provider,
		arg.ExternalID,
		arg.CachedMetaJson,
		arg.SyncStatus,
		arg.LastSyncedAt,
		arg.CreatedAt,
	)
	return err
}

const listBindingsBySlot = `-- name: ListBindingsBySlot :many
SELECT id, slot_id, account_id, provider, external_id, cached_meta_json, sync_status, last_synced_at, created_at FROM binding WHERE slot_id = ? ORDER BY created_at DESC
`

// binding queries
func (q *Queries) ListBindingsBySlot(ctx context.Context, slotID string) ([]Binding, error) {
	rows, err := q.db.QueryContext(ctx, listBindingsBySlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Binding
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.AccountID,
			&i.Provider,
			&i.ExternalID,
			&i.CachedMetaJson,
			&i.SyncStatus,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindingsBySlots = `-- name: ListBindingsBySlots :many
SELECT id, slot_id, account_id, provider, external_id, cached_meta_json, sync_status, last_synced_at, created_at FROM binding WHERE slot_id IN (/*SLOTS*/) ORDER BY slot_id, created_at DESC
`

func (q *Queries) ListBindingsBySlots(ctx context.Context, slotIDs []string) ([]Binding, error) {
	query := listBindingsBySlots
	var args []interface{}
	for _, id := range slotIDs {
		args = append(args, id)
	}
	// sqlite does not support array parameters; build positional placeholders
	placeholder := make([]string, len(slotIDs))
	for i := range placeholder {
		placeholder[i] = "?"
	}
	query = "SELECT id, slot_id, account_id, provider, external_id, cached_meta_json, sync_status, last_synced_at, created_at FROM binding WHERE slot_id IN (" + joinStrings(placeholder, ",") + ") ORDER BY slot_id, created_at DESC"

	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Binding
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.AccountID,
			&i.Provider,
			&i.ExternalID,
			&i.CachedMetaJson,
			&i.SyncStatus,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func joinStrings(elems []string, sep string) string {
	if len(elems) == 0 {
		return ""
	}
	n := len(sep) * (len(elems) - 1)
	for _, e := range elems {
		n += len(e)
	}
	var b []byte
	for i, e := range elems {
		if i > 0 {
			b = append(b, sep...)
		}
		b = append(b, []byte(e)...)
	}
	return string(b)
}

const updateBindingSyncStatus = `-- name: UpdateBindingSyncStatus :exec
UPDATE binding SET sync_status = ?, cached_meta_json = ?, last_synced_at = ? WHERE id = ?
`

type UpdateBindingSyncStatusParams struct {
	SyncStatus     string
	CachedMetaJson string
	LastSyncedAt   *string
	ID             string
}

func (q *Queries) UpdateBindingSyncStatus(ctx context.Context, arg UpdateBindingSyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBindingSyncStatus,
		arg.SyncStatus,
		arg.CachedMetaJson,
		arg.LastSyncedAt,
		arg.ID,
	)
	return err
}
