// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type OauthAuthorizationSession struct {
	ID                    string
	State                 string
	ProviderID            string
	Endpoint              string
	RedirectUri           string
	EncryptedCodeVerifier string
	Status                string
	EncryptedCredential   string
	TokenMetaJson         string
	RemoteIdentityJson    string
	ScopesJson            string
	PermissionsJson       string
	ErrorJson             string
	CreatedAt             string
	UpdatedAt             string
	ExpiresAt             string
	ConsumedAt            *string
}

type OauthClientConfiguration struct {
	ProviderID            string
	ClientID              string
	EncryptedClientSecret string
	AuthorizationUrl      string
	TokenUrl              string
	ScopesJson            string
	Pkce                  int64
	RedirectBaseUrl       string
	ProviderConfigJson    string
	CreatedAt             string
	UpdatedAt             string
}

type OperationRequest struct {
	ID                 string
	IdempotencyKey     string
	OperationType      string
	RequestHash        string
	Status             string
	ResourceInstanceID *string
	ResponseJson       string
	ErrorJson          string
	CreatedAt          string
	UpdatedAt          string
	ExpiresAt          *string
}

type Project struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type ProjectResource struct {
	ID                 string
	ProjectID          string
	ResourceInstanceID string
	Alias              string
	Purpose            string
	CreatedAt          string
	UpdatedAt          string
}

type ProviderConnection struct {
	ID                   string
	ProviderID           string
	Label                string
	Endpoint             string
	ScopeType            string
	ScopeID              string
	ScopeLabel           string
	ConfigJson           string
	EncryptedCredential  string
	RemoteIdentityJson   string
	PermissionsJson      string
	PermissionsCheckedAt *string
	CreatedAt            string
	UpdatedAt            string
	AuthMethod           string
}

type ResourceInstance struct {
	ID                  string
	ConnectionID        string
	ProviderProductID   string
	ResourceKind        string
	ExternalID          string
	ExternalUrl         string
	DisplayName         string
	LifecycleMode       string
	SpecJson            string
	ProviderConfigJson  string
	CachedMetaJson      string
	SyncStatus          string
	CapabilityStateJson string
	LastSyncedAt        *string
	CreatedAt           string
	UpdatedAt           string
}

type ResourceRelation struct {
	ID                     string
	FromResourceInstanceID string
	ToResourceInstanceID   string
	RelationType           string
	Origin                 string
	ConfigJson             string
	CreatedAt              string
}

type SchemaMetum struct {
	Key   string
	Value string
}
