// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Binding struct {
	ID             string
	SlotID         string
	ConnectionID   string
	Product        string
	ExternalID     string
	CachedMetaJson string
	SyncStatus     string
	LastSyncedAt   *string
	CreatedAt      string
}

type Project struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type ProviderConnection struct {
	ID                  string
	Provider            string
	Label               string
	Endpoint            string
	ConfigJson          string
	EncryptedCredential string
	RemoteIdentityJson  string
	CreatedAt           string
}

type Slot struct {
	ID         string
	ProjectID  string
	Role       string
	Name       string
	ConfigJson string
	CreatedAt  string
}