// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Binding struct {
	ID             string
	SlotID         string
	AccountID      string
	Provider       string
	ExternalID     string
	CachedMetaJson string
	SyncStatus     string
	LastSyncedAt   *string
	CreatedAt      string
}

type Project struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type ProviderAccount struct {
	ID             string
	Provider       string
	Label          string
	EncryptedToken string
	MetaJson       string
	CreatedAt      string
}

type Slot struct {
	ID         string
	ProjectID  string
	Type       string
	Name       string
	ConfigJson string
	CreatedAt  string
}
