// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_client_configuration.sql

package store

import (
	"context"
)

const deleteOAuthClientConfiguration = `-- name: DeleteOAuthClientConfiguration :execrows
DELETE FROM oauth_client_configuration WHERE provider_id = ?
`

func (q *Queries) DeleteOAuthClientConfiguration(ctx context.Context, providerID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOAuthClientConfiguration, providerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthClientConfiguration = `-- name: GetOAuthClientConfiguration :one
SELECT provider_id, client_id, encrypted_client_secret, authorization_url, token_url, scopes_json, pkce, redirect_base_url, provider_config_json, created_at, updated_at FROM oauth_client_configuration WHERE provider_id = ?
`

func (q *Queries) GetOAuthClientConfiguration(ctx context.Context, providerID string) (OauthClientConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClientConfiguration, providerID)
	var i OauthClientConfiguration
	err := row.Scan(
		&i.ProviderID,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.AuthorizationUrl,
		&i.TokenUrl,
		&i.ScopesJson,
		&i.Pkce,
		&i.RedirectBaseUrl,
		&i.ProviderConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthClientConfigurations = `-- name: ListOAuthClientConfigurations :many
SELECT provider_id, client_id, encrypted_client_secret, authorization_url, token_url, scopes_json, pkce, redirect_base_url, provider_config_json, created_at, updated_at FROM oauth_client_configuration ORDER BY provider_id
`

func (q *Queries) ListOAuthClientConfigurations(ctx context.Context) ([]OauthClientConfiguration, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthClientConfigurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClientConfiguration
	for rows.Next() {
		var i OauthClientConfiguration
		if err := rows.Scan(
			&i.ProviderID,
			&i.ClientID,
			&i.EncryptedClientSecret,
			&i.AuthorizationUrl,
			&i.TokenUrl,
			&i.ScopesJson,
			&i.Pkce,
			&i.RedirectBaseUrl,
			&i.ProviderConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOAuthClientConfiguration = `-- name: UpsertOAuthClientConfiguration :exec
INSERT INTO oauth_client_configuration (
    provider_id, client_id, encrypted_client_secret, authorization_url,
    token_url, scopes_json, pkce, redirect_base_url, provider_config_json,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(provider_id) DO UPDATE SET
    client_id = excluded.client_id,
    encrypted_client_secret = excluded.encrypted_client_secret,
    authorization_url = excluded.authorization_url,
    token_url = excluded.token_url,
    scopes_json = excluded.scopes_json,
    pkce = excluded.pkce,
    redirect_base_url = excluded.redirect_base_url,
    provider_config_json = excluded.provider_config_json,
    updated_at = excluded.updated_at
`

type UpsertOAuthClientConfigurationParams struct {
	ProviderID            string
	ClientID              string
	EncryptedClientSecret string
	AuthorizationUrl      string
	TokenUrl              string
	ScopesJson            string
	Pkce                  int64
	RedirectBaseUrl       string
	ProviderConfigJson    string
	CreatedAt             string
	UpdatedAt             string
}

func (q *Queries) UpsertOAuthClientConfiguration(ctx context.Context, arg UpsertOAuthClientConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, upsertOAuthClientConfiguration,
		arg.ProviderID,
		arg.ClientID,
		arg.EncryptedClientSecret,
		arg.AuthorizationUrl,
		arg.TokenUrl,
		arg.ScopesJson,
		arg.Pkce,
		arg.RedirectBaseUrl,
		arg.ProviderConfigJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
