// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_authorization.sql

package store

import (
	"context"
)

const authorizeOAuthSession = `-- name: AuthorizeOAuthSession :execrows
UPDATE oauth_authorization_session
SET status = 'authorized', encrypted_credential = ?, token_meta_json = ?,
    remote_identity_json = ?, scopes_json = ?, permissions_json = ?,
    error_json = '{}', updated_at = ?
WHERE id = ? AND status = 'pending' AND expires_at > ?
`

type AuthorizeOAuthSessionParams struct {
	EncryptedCredential string
	TokenMetaJson       string
	RemoteIdentityJson  string
	ScopesJson          string
	PermissionsJson     string
	UpdatedAt           string
	ID                  string
	ExpiresAt           string
}

func (q *Queries) AuthorizeOAuthSession(ctx context.Context, arg AuthorizeOAuthSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, authorizeOAuthSession,
		arg.EncryptedCredential,
		arg.TokenMetaJson,
		arg.RemoteIdentityJson,
		arg.ScopesJson,
		arg.PermissionsJson,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeOAuthSession = `-- name: ConsumeOAuthSession :execrows
UPDATE oauth_authorization_session
SET status = 'consumed', consumed_at = ?, updated_at = ?
WHERE id = ? AND status = 'authorized' AND expires_at > ?
`

type ConsumeOAuthSessionParams struct {
	ConsumedAt *string
	UpdatedAt  string
	ID         string
	ExpiresAt  string
}

func (q *Queries) ConsumeOAuthSession(ctx context.Context, arg ConsumeOAuthSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeOAuthSession,
		arg.ConsumedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOAuthSessions = `-- name: DeleteExpiredOAuthSessions :exec
DELETE FROM oauth_authorization_session
WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredOAuthSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOAuthSessions, expiresAt)
	return err
}

const failOAuthSession = `-- name: FailOAuthSession :execrows
UPDATE oauth_authorization_session
SET status = 'failed', error_json = ?, updated_at = ?
WHERE id = ? AND status = 'pending'
`

type FailOAuthSessionParams struct {
	ErrorJson string
	UpdatedAt string
	ID        string
}

func (q *Queries) FailOAuthSession(ctx context.Context, arg FailOAuthSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failOAuthSession, arg.ErrorJson, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthAuthorizationSession = `-- name: GetOAuthAuthorizationSession :one
SELECT id, state, provider_id, endpoint, redirect_uri, encrypted_code_verifier, status, encrypted_credential, token_meta_json, remote_identity_json, scopes_json, permissions_json, error_json, created_at, updated_at, expires_at, consumed_at FROM oauth_authorization_session WHERE id = ?
`

func (q *Queries) GetOAuthAuthorizationSession(ctx context.Context, id string) (OauthAuthorizationSession, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAuthorizationSession, id)
	var i OauthAuthorizationSession
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.ProviderID,
		&i.Endpoint,
		&i.RedirectUri,
		&i.EncryptedCodeVerifier,
		&i.Status,
		&i.EncryptedCredential,
		&i.TokenMetaJson,
		&i.RemoteIdentityJson,
		&i.ScopesJson,
		&i.PermissionsJson,
		&i.ErrorJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getOAuthAuthorizationSessionByState = `-- name: GetOAuthAuthorizationSessionByState :one
SELECT id, state, provider_id, endpoint, redirect_uri, encrypted_code_verifier, status, encrypted_credential, token_meta_json, remote_identity_json, scopes_json, permissions_json, error_json, created_at, updated_at, expires_at, consumed_at FROM oauth_authorization_session WHERE state = ?
`

func (q *Queries) GetOAuthAuthorizationSessionByState(ctx context.Context, state string) (OauthAuthorizationSession, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAuthorizationSessionByState, state)
	var i OauthAuthorizationSession
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.ProviderID,
		&i.Endpoint,
		&i.RedirectUri,
		&i.EncryptedCodeVerifier,
		&i.Status,
		&i.EncryptedCredential,
		&i.TokenMetaJson,
		&i.RemoteIdentityJson,
		&i.ScopesJson,
		&i.PermissionsJson,
		&i.ErrorJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertOAuthAuthorizationSession = `-- name: InsertOAuthAuthorizationSession :exec
INSERT INTO oauth_authorization_session (
    id, state, provider_id, endpoint, redirect_uri, encrypted_code_verifier,
    status, encrypted_credential, token_meta_json, remote_identity_json,
    scopes_json, permissions_json, error_json, created_at, updated_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOAuthAuthorizationSessionParams struct {
	ID                    string
	State                 string
	ProviderID            string
	Endpoint              string
	RedirectUri           string
	EncryptedCodeVerifier string
	Status                string
	EncryptedCredential   string
	TokenMetaJson         string
	RemoteIdentityJson    string
	ScopesJson            string
	PermissionsJson       string
	ErrorJson             string
	CreatedAt             string
	UpdatedAt             string
	ExpiresAt             string
}

func (q *Queries) InsertOAuthAuthorizationSession(ctx context.Context, arg InsertOAuthAuthorizationSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthAuthorizationSession,
		arg.ID,
		arg.State,
		arg.ProviderID,
		arg.Endpoint,
		arg.RedirectUri,
		arg.EncryptedCodeVerifier,
		arg.Status,
		arg.EncryptedCredential,
		arg.TokenMetaJson,
		arg.RemoteIdentityJson,
		arg.ScopesJson,
		arg.PermissionsJson,
		arg.ErrorJson,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}
