// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_request.sql

package store

import (
	"context"
)

const deleteExpiredOperationRequests = `-- name: DeleteExpiredOperationRequests :exec
DELETE FROM operation_request
WHERE expires_at IS NOT NULL AND expires_at < ? AND status <> 'unknown'
`

func (q *Queries) DeleteExpiredOperationRequests(ctx context.Context, expiresAt *string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOperationRequests, expiresAt)
	return err
}

const getOperationRequest = `-- name: GetOperationRequest :one
SELECT id, idempotency_key, operation_type, request_hash, status, resource_instance_id, response_json, error_json, created_at, updated_at, expires_at FROM operation_request WHERE id = ?
`

func (q *Queries) GetOperationRequest(ctx context.Context, id string) (OperationRequest, error) {
	row := q.db.QueryRowContext(ctx, getOperationRequest, id)
	var i OperationRequest
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.OperationType,
		&i.RequestHash,
		&i.Status,
		&i.ResourceInstanceID,
		&i.ResponseJson,
		&i.ErrorJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOperationRequestByKey = `-- name: GetOperationRequestByKey :one
SELECT id, idempotency_key, operation_type, request_hash, status, resource_instance_id, response_json, error_json, created_at, updated_at, expires_at FROM operation_request WHERE idempotency_key = ?
`

func (q *Queries) GetOperationRequestByKey(ctx context.Context, idempotencyKey string) (OperationRequest, error) {
	row := q.db.QueryRowContext(ctx, getOperationRequestByKey, idempotencyKey)
	var i OperationRequest
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.OperationType,
		&i.RequestHash,
		&i.Status,
		&i.ResourceInstanceID,
		&i.ResponseJson,
		&i.ErrorJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertOperationRequest = `-- name: InsertOperationRequest :exec
INSERT INTO operation_request (
    id, idempotency_key, operation_type, request_hash, status,
    resource_instance_id, response_json, error_json, created_at, updated_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOperationRequestParams struct {
	ID                 string
	IdempotencyKey     string
	OperationType      string
	RequestHash        string
	Status             string
	ResourceInstanceID *string
	ResponseJson       string
	ErrorJson          string
	CreatedAt          string
	UpdatedAt          string
	ExpiresAt          *string
}

func (q *Queries) InsertOperationRequest(ctx context.Context, arg InsertOperationRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertOperationRequest,
		arg.ID,
		arg.IdempotencyKey,
		arg.OperationType,
		arg.RequestHash,
		arg.Status,
		arg.ResourceInstanceID,
		arg.ResponseJson,
		arg.ErrorJson,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const updateOperationRequest = `-- name: UpdateOperationRequest :exec
UPDATE operation_request
SET status = ?, resource_instance_id = ?, response_json = ?, error_json = ?,
    updated_at = ?, expires_at = ?
WHERE id = ?
`

type UpdateOperationRequestParams struct {
	Status             string
	ResourceInstanceID *string
	ResponseJson       string
	ErrorJson          string
	UpdatedAt          string
	ExpiresAt          *string
	ID                 string
}

func (q *Queries) UpdateOperationRequest(ctx context.Context, arg UpdateOperationRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateOperationRequest,
		arg.Status,
		arg.ResourceInstanceID,
		arg.ResponseJson,
		arg.ErrorJson,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
