// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_resource.sql

package store

import (
	"context"
)

const countProjectResourcesByInstance = `-- name: CountProjectResourcesByInstance :one
SELECT COUNT(*) FROM project_resource WHERE resource_instance_id = ?
`

func (q *Queries) CountProjectResourcesByInstance(ctx context.Context, resourceInstanceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectResourcesByInstance, resourceInstanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProjectResource = `-- name: DeleteProjectResource :execrows
DELETE FROM project_resource WHERE id = ? AND project_id = ?
`

type DeleteProjectResourceParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteProjectResource(ctx context.Context, arg DeleteProjectResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProjectResource, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProjectResource = `-- name: GetProjectResource :one
SELECT id, project_id, resource_instance_id, alias, role, purpose, created_at, updated_at FROM project_resource WHERE id = ?
`

func (q *Queries) GetProjectResource(ctx context.Context, id string) (ProjectResource, error) {
	row := q.db.QueryRowContext(ctx, getProjectResource, id)
	var i ProjectResource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceInstanceID,
		&i.Alias,
		&i.Role,
		&i.Purpose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectResource = `-- name: InsertProjectResource :exec
INSERT INTO project_resource (
    id, project_id, resource_instance_id, alias, role, purpose, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProjectResourceParams struct {
	ID                 string
	ProjectID          string
	ResourceInstanceID string
	Alias              string
	Role               string
	Purpose            string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) InsertProjectResource(ctx context.Context, arg InsertProjectResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectResource,
		arg.ID,
		arg.ProjectID,
		arg.ResourceInstanceID,
		arg.Alias,
		arg.Role,
		arg.Purpose,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listProjectResources = `-- name: ListProjectResources :many
SELECT id, project_id, resource_instance_id, alias, role, purpose, created_at, updated_at FROM project_resource WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListProjectResources(ctx context.Context, projectID string) ([]ProjectResource, error) {
	rows, err := q.db.QueryContext(ctx, listProjectResources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectResource
	for rows.Next() {
		var i ProjectResource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceInstanceID,
			&i.Alias,
			&i.Role,
			&i.Purpose,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectResource = `-- name: UpdateProjectResource :exec
UPDATE project_resource SET alias = ?, role = ?, purpose = ?, updated_at = ? WHERE id = ?
`

type UpdateProjectResourceParams struct {
	Alias     string
	Role      string
	Purpose   string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateProjectResource(ctx context.Context, arg UpdateProjectResourceParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectResource,
		arg.Alias,
		arg.Role,
		arg.Purpose,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
