// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_connection.sql

package store

import (
	"context"
)

const deleteProviderConnection = `-- name: DeleteProviderConnection :exec
DELETE FROM provider_connection WHERE id = ?
`

func (q *Queries) DeleteProviderConnection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProviderConnection, id)
	return err
}

const getProviderConnection = `-- name: GetProviderConnection :one
SELECT id, provider, label, endpoint, config_json, encrypted_credential, remote_identity_json, created_at FROM provider_connection WHERE id = ?
`

func (q *Queries) GetProviderConnection(ctx context.Context, id string) (ProviderConnection, error) {
	row := q.db.QueryRowContext(ctx, getProviderConnection, id)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.Endpoint,
		&i.ConfigJson,
		&i.EncryptedCredential,
		&i.RemoteIdentityJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderConnection = `-- name: InsertProviderConnection :exec
INSERT INTO provider_connection (id, provider, label, endpoint, config_json, encrypted_credential, remote_identity_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProviderConnectionParams struct {
	ID                  string
	Provider            string
	Label               string
	Endpoint            string
	ConfigJson          string
	EncryptedCredential string
	RemoteIdentityJson  string
	CreatedAt           string
}

func (q *Queries) InsertProviderConnection(ctx context.Context, arg InsertProviderConnectionParams) error {
	_, err := q.db.ExecContext(ctx, insertProviderConnection,
		arg.ID,
		arg.Provider,
		arg.Label,
		arg.Endpoint,
		arg.ConfigJson,
		arg.EncryptedCredential,
		arg.RemoteIdentityJson,
		arg.CreatedAt,
	)
	return err
}

const listProviderConnections = `-- name: ListProviderConnections :many
SELECT id, provider, label, endpoint, config_json, encrypted_credential, remote_identity_json, created_at FROM provider_connection ORDER BY created_at DESC
`

// provider_connection queries
func (q *Queries) ListProviderConnections(ctx context.Context) ([]ProviderConnection, error) {
	rows, err := q.db.QueryContext(ctx, listProviderConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderConnection
	for rows.Next() {
		var i ProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.Endpoint,
			&i.ConfigJson,
			&i.EncryptedCredential,
			&i.RemoteIdentityJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderConnectionCredential = `-- name: GetProviderConnectionCredential :one
SELECT encrypted_credential FROM provider_connection WHERE id = ?
`

func (q *Queries) GetProviderConnectionCredential(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProviderConnectionCredential, id)
	var encrypted_credential string
	err := row.Scan(&encrypted_credential)
	return encrypted_credential, err
}