// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_account.sql

package store

import (
	"context"
)

const deleteProviderAccount = `-- name: DeleteProviderAccount :exec
DELETE FROM provider_account WHERE id = ?
`

func (q *Queries) DeleteProviderAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProviderAccount, id)
	return err
}

const getProviderAccount = `-- name: GetProviderAccount :one
SELECT id, provider, label, encrypted_token, meta_json, created_at FROM provider_account WHERE id = ?
`

func (q *Queries) GetProviderAccount(ctx context.Context, id string) (ProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getProviderAccount, id)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.EncryptedToken,
		&i.MetaJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderAccount = `-- name: InsertProviderAccount :exec
INSERT INTO provider_account (id, provider, label, encrypted_token, meta_json, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertProviderAccountParams struct {
	ID             string
	Provider       string
	Label          string
	EncryptedToken string
	MetaJson       string
	CreatedAt      string
}

func (q *Queries) InsertProviderAccount(ctx context.Context, arg InsertProviderAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertProviderAccount,
		arg.ID,
		arg.Provider,
		arg.Label,
		arg.EncryptedToken,
		arg.MetaJson,
		arg.CreatedAt,
	)
	return err
}

const listProviderAccounts = `-- name: ListProviderAccounts :many
SELECT id, provider, label, encrypted_token, meta_json, created_at FROM provider_account ORDER BY created_at DESC
`

// provider_account queries
func (q *Queries) ListProviderAccounts(ctx context.Context) ([]ProviderAccount, error) {
	rows, err := q.db.QueryContext(ctx, listProviderAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderAccount
	for rows.Next() {
		var i ProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.EncryptedToken,
			&i.MetaJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
