// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	DeleteBinding(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteProviderConnection(ctx context.Context, id string) error
	DeleteSlot(ctx context.Context, id string) error
	FanOutBindingsByAccountExternal(ctx context.Context, arg FanOutBindingsByAccountExternalParams) ([]Binding, error)
	GetBinding(ctx context.Context, id string) (Binding, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectByName(ctx context.Context, name string) (Project, error)
	GetProviderConnection(ctx context.Context, id string) (ProviderConnection, error)
	GetSlot(ctx context.Context, id string) (Slot, error)
	InsertBinding(ctx context.Context, arg InsertBindingParams) error
	InsertProject(ctx context.Context, arg InsertProjectParams) error
	InsertProviderConnection(ctx context.Context, arg InsertProviderConnectionParams) error
	InsertSlot(ctx context.Context, arg InsertSlotParams) error
	// binding queries
	ListBindingsBySlot(ctx context.Context, slotID string) ([]Binding, error)
	ListBindingsBySlots(ctx context.Context, slotIDs []string) ([]Binding, error)
	// project queries
	ListProjects(ctx context.Context) ([]Project, error)
	// provider_connection queries
	ListProviderConnections(ctx context.Context) ([]ProviderConnection, error)
	// slot queries
	ListSlotsByProject(ctx context.Context, projectID string) ([]Slot, error)
	UpdateBindingSyncStatus(ctx context.Context, arg UpdateBindingSyncStatusParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateSlot(ctx context.Context, arg UpdateSlotParams) error
	UpdateSlotConfig(ctx context.Context, arg UpdateSlotConfigParams) error
}

var _ Querier = (*Queries)(nil)