// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_relation.sql

package store

import (
	"context"
)

const countRelationsTo = `-- name: CountRelationsTo :one
SELECT COUNT(*) FROM resource_relation WHERE to_resource_instance_id = ?
`

func (q *Queries) CountRelationsTo(ctx context.Context, toResourceInstanceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRelationsTo, toResourceInstanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteResourceRelation = `-- name: DeleteResourceRelation :execrows
DELETE FROM resource_relation WHERE id = ?
`

func (q *Queries) DeleteResourceRelation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteResourceRelation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getResourceRelation = `-- name: GetResourceRelation :one
SELECT id, from_resource_instance_id, to_resource_instance_id, relation_type, origin, config_json, created_at FROM resource_relation WHERE id = ?
`

func (q *Queries) GetResourceRelation(ctx context.Context, id string) (ResourceRelation, error) {
	row := q.db.QueryRowContext(ctx, getResourceRelation, id)
	var i ResourceRelation
	err := row.Scan(
		&i.ID,
		&i.FromResourceInstanceID,
		&i.ToResourceInstanceID,
		&i.RelationType,
		&i.Origin,
		&i.ConfigJson,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceRelation = `-- name: GetSourceRelation :one
SELECT id, from_resource_instance_id, to_resource_instance_id, relation_type, origin, config_json, created_at FROM resource_relation
WHERE from_resource_instance_id = ? AND relation_type = 'source_repo'
`

func (q *Queries) GetSourceRelation(ctx context.Context, fromResourceInstanceID string) (ResourceRelation, error) {
	row := q.db.QueryRowContext(ctx, getSourceRelation, fromResourceInstanceID)
	var i ResourceRelation
	err := row.Scan(
		&i.ID,
		&i.FromResourceInstanceID,
		&i.ToResourceInstanceID,
		&i.RelationType,
		&i.Origin,
		&i.ConfigJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertResourceRelation = `-- name: InsertResourceRelation :exec
INSERT INTO resource_relation (
    id, from_resource_instance_id, to_resource_instance_id,
    relation_type, origin, config_json, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertResourceRelationParams struct {
	ID                     string
	FromResourceInstanceID string
	ToResourceInstanceID   string
	RelationType           string
	Origin                 string
	ConfigJson             string
	CreatedAt              string
}

func (q *Queries) InsertResourceRelation(ctx context.Context, arg InsertResourceRelationParams) error {
	_, err := q.db.ExecContext(ctx, insertResourceRelation,
		arg.ID,
		arg.FromResourceInstanceID,
		arg.ToResourceInstanceID,
		arg.RelationType,
		arg.Origin,
		arg.ConfigJson,
		arg.CreatedAt,
	)
	return err
}

const listRelationsFrom = `-- name: ListRelationsFrom :many
SELECT id, from_resource_instance_id, to_resource_instance_id, relation_type, origin, config_json, created_at FROM resource_relation WHERE from_resource_instance_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListRelationsFrom(ctx context.Context, fromResourceInstanceID string) ([]ResourceRelation, error) {
	rows, err := q.db.QueryContext(ctx, listRelationsFrom, fromResourceInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRelation
	for rows.Next() {
		var i ResourceRelation
		if err := rows.Scan(
			&i.ID,
			&i.FromResourceInstanceID,
			&i.ToResourceInstanceID,
			&i.RelationType,
			&i.Origin,
			&i.ConfigJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsTo = `-- name: ListRelationsTo :many
SELECT id, from_resource_instance_id, to_resource_instance_id, relation_type, origin, config_json, created_at FROM resource_relation WHERE to_resource_instance_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListRelationsTo(ctx context.Context, toResourceInstanceID string) ([]ResourceRelation, error) {
	rows, err := q.db.QueryContext(ctx, listRelationsTo, toResourceInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRelation
	for rows.Next() {
		var i ResourceRelation
		if err := rows.Scan(
			&i.ID,
			&i.FromResourceInstanceID,
			&i.ToResourceInstanceID,
			&i.RelationType,
			&i.Origin,
			&i.ConfigJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceRelations = `-- name: ListResourceRelations :many
SELECT id, from_resource_instance_id, to_resource_instance_id, relation_type, origin, config_json, created_at FROM resource_relation ORDER BY created_at ASC
`

func (q *Queries) ListResourceRelations(ctx context.Context) ([]ResourceRelation, error) {
	rows, err := q.db.QueryContext(ctx, listResourceRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRelation
	for rows.Next() {
		var i ResourceRelation
		if err := rows.Scan(
			&i.ID,
			&i.FromResourceInstanceID,
			&i.ToResourceInstanceID,
			&i.RelationType,
			&i.Origin,
			&i.ConfigJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
