// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_instance.sql

package store

import (
	"context"
)

const countResourceInstancesByConnection = `-- name: CountResourceInstancesByConnection :one
SELECT COUNT(*) FROM resource_instance WHERE connection_id = ?
`

func (q *Queries) CountResourceInstancesByConnection(ctx context.Context, connectionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourceInstancesByConnection, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteResourceInstance = `-- name: DeleteResourceInstance :execrows
DELETE FROM resource_instance WHERE id = ?
`

func (q *Queries) DeleteResourceInstance(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteResourceInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getResourceInstance = `-- name: GetResourceInstance :one
SELECT id, connection_id, provider_product_id, resource_kind, external_id, external_url, display_name, lifecycle_mode, spec_json, provider_config_json, cached_meta_json, sync_status, capability_state_json, last_synced_at, created_at, updated_at FROM resource_instance WHERE id = ?
`

func (q *Queries) GetResourceInstance(ctx context.Context, id string) (ResourceInstance, error) {
	row := q.db.QueryRowContext(ctx, getResourceInstance, id)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderProductID,
		&i.ResourceKind,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.DisplayName,
		&i.LifecycleMode,
		&i.SpecJson,
		&i.ProviderConfigJson,
		&i.CachedMetaJson,
		&i.SyncStatus,
		&i.CapabilityStateJson,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceInstanceByRemote = `-- name: GetResourceInstanceByRemote :one
SELECT id, connection_id, provider_product_id, resource_kind, external_id, external_url, display_name, lifecycle_mode, spec_json, provider_config_json, cached_meta_json, sync_status, capability_state_json, last_synced_at, created_at, updated_at FROM resource_instance
WHERE connection_id = ? AND provider_product_id = ? AND external_id = ?
`

type GetResourceInstanceByRemoteParams struct {
	ConnectionID      string
	ProviderProductID string
	ExternalID        string
}

func (q *Queries) GetResourceInstanceByRemote(ctx context.Context, arg GetResourceInstanceByRemoteParams) (ResourceInstance, error) {
	row := q.db.QueryRowContext(ctx, getResourceInstanceByRemote, arg.ConnectionID, arg.ProviderProductID, arg.ExternalID)
	var i ResourceInstance
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderProductID,
		&i.ResourceKind,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.DisplayName,
		&i.LifecycleMode,
		&i.SpecJson,
		&i.ProviderConfigJson,
		&i.CachedMetaJson,
		&i.SyncStatus,
		&i.CapabilityStateJson,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertResourceInstance = `-- name: InsertResourceInstance :exec
INSERT INTO resource_instance (
    id, connection_id, provider_product_id, resource_kind, external_id,
    external_url, display_name, lifecycle_mode, spec_json, provider_config_json,
    cached_meta_json, sync_status, capability_state_json, last_synced_at,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertResourceInstanceParams struct {
	ID                  string
	ConnectionID        string
	ProviderProductID   string
	ResourceKind        string
	ExternalID          string
	ExternalUrl         string
	DisplayName         string
	LifecycleMode       string
	SpecJson            string
	ProviderConfigJson  string
	CachedMetaJson      string
	SyncStatus          string
	CapabilityStateJson string
	LastSyncedAt        *string
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) InsertResourceInstance(ctx context.Context, arg InsertResourceInstanceParams) error {
	_, err := q.db.ExecContext(ctx, insertResourceInstance,
		arg.ID,
		arg.ConnectionID,
		arg.ProviderProductID,
		arg.ResourceKind,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.DisplayName,
		arg.LifecycleMode,
		arg.SpecJson,
		arg.ProviderConfigJson,
		arg.CachedMetaJson,
		arg.SyncStatus,
		arg.CapabilityStateJson,
		arg.LastSyncedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listResourceInstances = `-- name: ListResourceInstances :many
SELECT id, connection_id, provider_product_id, resource_kind, external_id, external_url, display_name, lifecycle_mode, spec_json, provider_config_json, cached_meta_json, sync_status, capability_state_json, last_synced_at, created_at, updated_at FROM resource_instance ORDER BY created_at DESC
`

func (q *Queries) ListResourceInstances(ctx context.Context) ([]ResourceInstance, error) {
	rows, err := q.db.QueryContext(ctx, listResourceInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceInstance
	for rows.Next() {
		var i ResourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ProviderProductID,
			&i.ResourceKind,
			&i.ExternalID,
			&i.ExternalUrl,
			&i.DisplayName,
			&i.LifecycleMode,
			&i.SpecJson,
			&i.ProviderConfigJson,
			&i.CachedMetaJson,
			&i.SyncStatus,
			&i.CapabilityStateJson,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceInstancesByConnection = `-- name: ListResourceInstancesByConnection :many
SELECT id, connection_id, provider_product_id, resource_kind, external_id, external_url, display_name, lifecycle_mode, spec_json, provider_config_json, cached_meta_json, sync_status, capability_state_json, last_synced_at, created_at, updated_at FROM resource_instance WHERE connection_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListResourceInstancesByConnection(ctx context.Context, connectionID string) ([]ResourceInstance, error) {
	rows, err := q.db.QueryContext(ctx, listResourceInstancesByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceInstance
	for rows.Next() {
		var i ResourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ProviderProductID,
			&i.ResourceKind,
			&i.ExternalID,
			&i.ExternalUrl,
			&i.DisplayName,
			&i.LifecycleMode,
			&i.SpecJson,
			&i.ProviderConfigJson,
			&i.CachedMetaJson,
			&i.SyncStatus,
			&i.CapabilityStateJson,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceInstanceLifecycle = `-- name: UpdateResourceInstanceLifecycle :exec
UPDATE resource_instance SET lifecycle_mode = ?, updated_at = ? WHERE id = ?
`

type UpdateResourceInstanceLifecycleParams struct {
	LifecycleMode string
	UpdatedAt     string
	ID            string
}

func (q *Queries) UpdateResourceInstanceLifecycle(ctx context.Context, arg UpdateResourceInstanceLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, updateResourceInstanceLifecycle, arg.LifecycleMode, arg.UpdatedAt, arg.ID)
	return err
}

const updateResourceInstanceSync = `-- name: UpdateResourceInstanceSync :exec
UPDATE resource_instance
SET external_url = ?, display_name = ?, cached_meta_json = ?, sync_status = ?,
    capability_state_json = ?, last_synced_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateResourceInstanceSyncParams struct {
	ExternalUrl         string
	DisplayName         string
	CachedMetaJson      string
	SyncStatus          string
	CapabilityStateJson string
	LastSyncedAt        *string
	UpdatedAt           string
	ID                  string
}

func (q *Queries) UpdateResourceInstanceSync(ctx context.Context, arg UpdateResourceInstanceSyncParams) error {
	_, err := q.db.ExecContext(ctx, updateResourceInstanceSync,
		arg.ExternalUrl,
		arg.DisplayName,
		arg.CachedMetaJson,
		arg.SyncStatus,
		arg.CapabilityStateJson,
		arg.LastSyncedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
