// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slot.sql

package store

import (
	"context"
)

const deleteSlot = `-- name: DeleteSlot :exec
DELETE FROM slot WHERE id = ?
`

func (q *Queries) DeleteSlot(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSlot, id)
	return err
}

const getSlot = `-- name: GetSlot :one
SELECT id, project_id, type, name, config_json, created_at FROM slot WHERE id = ?
`

func (q *Queries) GetSlot(ctx context.Context, id string) (Slot, error) {
	row := q.db.QueryRowContext(ctx, getSlot, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.ConfigJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :exec
INSERT INTO slot (id, project_id, type, name, config_json, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSlotParams struct {
	ID         string
	ProjectID  string
	Type       string
	Name       string
	ConfigJson string
	CreatedAt  string
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) error {
	_, err := q.db.ExecContext(ctx, insertSlot,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Name,
		arg.ConfigJson,
		arg.CreatedAt,
	)
	return err
}

const listSlotsByProject = `-- name: ListSlotsByProject :many
SELECT id, project_id, type, name, config_json, created_at FROM slot WHERE project_id = ? ORDER BY created_at DESC
`

// slot queries
func (q *Queries) ListSlotsByProject(ctx context.Context, projectID string) ([]Slot, error) {
	rows, err := q.db.QueryContext(ctx, listSlotsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Name,
			&i.ConfigJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlotConfig = `-- name: UpdateSlotConfig :exec
UPDATE slot SET config_json = ? WHERE id = ?
`

type UpdateSlotConfigParams struct {
	ConfigJson string
	ID         string
}

func (q *Queries) UpdateSlotConfig(ctx context.Context, arg UpdateSlotConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateSlotConfig, arg.ConfigJson, arg.ID)
	return err
}

const updateSlot = `-- name: UpdateSlot :exec
UPDATE slot SET name = ?, config_json = ? WHERE id = ?
`

type UpdateSlotParams struct {
	Name       string
	ConfigJson string
	ID         string
}

func (q *Queries) UpdateSlot(ctx context.Context, arg UpdateSlotParams) error {
	_, err := q.db.ExecContext(ctx, updateSlot, arg.Name, arg.ConfigJson, arg.ID)
	return err
}
