// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"log/slog"

	_ "modernc.org/sqlite"

	"github.com/pressly/goose/v3"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

var ErrLegacySchema = errors.New("legacy slot/binding schema detected; back up and remove the database before starting Mevius")

// Open opens a SQLite database at the given path with WAL mode, busy timeout,
// and MaxOpenConns(1). It runs pending goose migrations before returning.
func Open(path string) (*sql.DB, error) {
	dsn := fmt.Sprintf("file:%s?_journal_mode=WAL&_busy_timeout=5000&_foreign_keys=1", path)
	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("sqlite open: %w", err)
	}

	db.SetMaxOpenConns(1)

	var legacyTables int
	if err := db.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name IN ('slot', 'binding')`).Scan(&legacyTables); err != nil {
		db.Close()
		return nil, fmt.Errorf("inspect sqlite schema: %w", err)
	}
	var hasEpochTable int
	if err := db.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = 'schema_meta'`).Scan(&hasEpochTable); err != nil {
		db.Close()
		return nil, fmt.Errorf("inspect sqlite schema epoch: %w", err)
	}
	if legacyTables > 0 && hasEpochTable == 0 {
		db.Close()
		return nil, ErrLegacySchema
	}

	goose.SetBaseFS(migrationsFS)
	goose.SetLogger(goose.NopLogger())
	if err := goose.SetDialect("sqlite3"); err != nil {
		db.Close()
		return nil, fmt.Errorf("goose dialect: %w", err)
	}
	if err := goose.Up(db, "migrations", goose.WithAllowMissing()); err != nil {
		db.Close()
		return nil, fmt.Errorf("goose up: %w", err)
	}

	var epoch string
	if err := db.QueryRow(`SELECT value FROM schema_meta WHERE key = 'schema_epoch'`).Scan(&epoch); err != nil || epoch != "4" {
		db.Close()
		if err != nil {
			return nil, fmt.Errorf("validate schema epoch: %w", err)
		}
		return nil, fmt.Errorf("unsupported schema epoch %q", epoch)
	}

	slog.Info("store: database migrated", "path", path)
	return db, nil
}
