import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { Plus, RefreshCw } from 'lucide-react'
import { Dialog } from 'radix-ui'
import { apiFetch, idempotencyKey, type Catalog, type Connection, type ExternalResource, type ResourceInstance } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const kindLabels:Record<string,string>={git_repo:'Repository',ci_pipeline:'CI pipeline',page:'Page',serverless_service:'Serverless',dns_zone:'DNS zone'}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full border px-2 py-0.5 text-[11px] text-muted-foreground">{children}</span>}

function Inventory(){const qc=useQueryClient();const[open,setOpen]=useState(false);const[productID,setProductID]=useState('');const[connectionID,setConnectionID]=useState('');const[mode,setMode]=useState<'import'|'create'>('import');const[parentID,setParentID]=useState('');const[sourceID,setSourceID]=useState('');const[name,setName]=useState('');const[selected,setSelected]=useState<ExternalResource|null>(null);const[discovered,setDiscovered]=useState<ExternalResource[]>([]);const[error,setError]=useState('');const{data:catalog}=useQuery({queryKey:['catalog'],queryFn:()=>apiFetch<Catalog>('/catalog/providers')});const{data:connections=[]}=useQuery({queryKey:['connections'],queryFn:()=>apiFetch<Connection[]>('/connections')});const{data:resources=[]}=useQuery({queryKey:['resources'],queryFn:()=>apiFetch<ResourceInstance[]>('/resource-instances')});const products=useMemo(()=>catalog?.providers.flatMap(item=>item.products)??[],[catalog]);const product=products.find(item=>item.id===productID);const validConnections=connections.filter(item=>item.provider_id===product?.provider_id);const repos=resources.filter(item=>item.resource_kind==='git_repo');const canCreate=product?.capabilities.includes('create')??false;
const discover=useMutation({mutationFn:()=>apiFetch<ExternalResource[]>(`/connections/${connectionID}/products/${productID}/resources${parentID?`?parent_instance_id=${encodeURIComponent(parentID)}`:''}`),onSuccess:value=>{setDiscovered(value);setError('')},onError:(e:Error)=>setError(e.message)});const save=useMutation({mutationFn:async()=>{if(mode==='import'){if(!selected)throw new Error('Select a remote resource');return apiFetch<ResourceInstance>('/resource-instances/import',{method:'POST',body:JSON.stringify({connection_id:connectionID,provider_product_id:productID,external_id:selected.external_id,provider_config:selected.provider_config,parent_instance_id:parentID||undefined})})}const spec=product?.resource_kind==='git_repo'?{name,private:false}:{name,source_repo_instance_id:sourceID,production_branch:'main'};return apiFetch<ResourceInstance>('/resource-instances',{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({connection_id:connectionID,provider_product_id:productID,spec,source_repo_instance_id:sourceID||undefined})})},onSuccess:()=>{qc.invalidateQueries({queryKey:['resources']});reset();setOpen(false)},onError:(e:Error)=>setError(e.message)});function reset(){setProductID('');setConnectionID('');setParentID('');setSourceID('');setName('');setSelected(null);setDiscovered([]);setError('');setMode('import')}
return <div><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-muted-foreground">Global resources</p><h1 className="mt-2 text-2xl font-medium">Inventory</h1><p className="mt-1 text-sm text-muted-foreground">One remote resource, reusable across projects.</p></div><Button onClick={()=>setOpen(true)}><Plus className="size-4"/>Add resource</Button></div><div className="overflow-hidden rounded-xl border"><div className="grid grid-cols-[1fr_150px_130px_110px] border-b bg-muted/30 px-5 py-2 text-xs text-muted-foreground"><span>Resource</span><span>Product</span><span>Lifecycle</span><span>Status</span></div>{resources.map(item=><Link key={item.id} to={`/inventory/${item.id}`} className="grid grid-cols-[1fr_150px_130px_110px] items-center border-b px-5 py-4 last:border-0 hover:bg-muted/30"><div><p className="font-medium">{item.display_name}</p><p className="text-xs text-muted-foreground">{kindLabels[item.resource_kind]??item.resource_kind} · {item.external_id}</p></div><span className="text-xs">{item.provider_product_id}</span><span><Badge>{item.lifecycle_mode}</Badge></span><span className="text-xs text-muted-foreground">{item.sync_status}</span></Link>)}{resources.length===0&&<p className="p-12 text-center text-sm text-muted-foreground">No resources have been imported or created.</p>}</div>
<Dialog.Root open={open} onOpenChange={value=>{setOpen(value);if(!value)reset()}}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/25"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[88vh] w-[min(94vw,560px)] -translate-x-1/2 -translate-y-1/2 overflow-auto rounded-xl border bg-background p-6 shadow-xl"><Dialog.Title className="mb-5 text-lg font-medium">Add resource</Dialog.Title><div className="space-y-4"><label className="block text-sm">Product<select className="mt-1 h-9 w-full rounded-md border bg-background px-3" value={productID} onChange={e=>{setProductID(e.target.value);setConnectionID('');setDiscovered([])}}><option value="">Choose a product</option>{products.map(item=><option key={item.id} value={item.id}>{item.display_name} · {item.provider_id}</option>)}</select></label><label className="block text-sm">Scoped connection<select className="mt-1 h-9 w-full rounded-md border bg-background px-3" value={connectionID} onChange={e=>setConnectionID(e.target.value)}><option value="">Choose a connection</option>{validConnections.map(item=><option key={item.id} value={item.id}>{item.label} · {item.scope.label}</option>)}</select></label>{canCreate&&<div className="flex gap-2"><Button variant={mode==='import'?'default':'outline'} onClick={()=>setMode('import')}>Discover & import</Button><Button variant={mode==='create'?'default':'outline'} onClick={()=>setMode('create')}>Create managed</Button></div>}{mode==='import'?<>{product?.resource_kind==='ci_pipeline'&&<RepoSelect label="Parent repository" value={parentID} onChange={setParentID} repos={repos}/>}<Button variant="outline" disabled={!connectionID||discover.isPending||(product?.resource_kind==='ci_pipeline'&&!parentID)} onClick={()=>discover.mutate()}><RefreshCw className="size-4"/>Discover</Button><div className="space-y-2">{discovered.map(item=><button key={item.external_id} onClick={()=>setSelected(item)} className={`w-full rounded-lg border p-3 text-left text-sm ${selected?.external_id===item.external_id?'border-foreground':'border-border'}`}><span className="font-medium">{item.display_name}</span><span className="ml-2 text-xs text-muted-foreground">{item.external_id}</span></button>)}</div></>:<><label className="block text-sm">Name<Input className="mt-1" value={name} onChange={e=>setName(e.target.value)}/></label>{product?.resource_kind==='page'&&<RepoSelect label="Source repository" value={sourceID} onChange={setSourceID} repos={repos}/>}</>} {error&&<p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Dialog.Close asChild><Button variant="outline">Cancel</Button></Dialog.Close><Button disabled={save.isPending||!connectionID||(mode==='import'&&!selected)||(mode==='create'&&!name)} onClick={()=>save.mutate()}>{save.isPending?'Saving…':mode==='import'?'Import':'Create'}</Button></div></div></Dialog.Content></Dialog.Portal></Dialog.Root></div>}
function RepoSelect({label,value,onChange,repos}:{label:string;value:string;onChange:(value:string)=>void;repos:ResourceInstance[]}){return <label className="block text-sm">{label}<select className="mt-1 h-9 w-full rounded-md border bg-background px-3" value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose a repository</option>{repos.map(repo=><option key={repo.id} value={repo.id}>{repo.display_name}</option>)}</select></label>}
export default Inventory
